---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
  # Добавим ключ репозитория для последующей работы с ним
  - name: Add APT key
    apt_key:
      id: 42F3E95A2C4F08279C4960ADD68FA50FEA312927
      keyserver: keyserver.ubuntu.com

  # Подключаем репозиторий с пакетами mongodb
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  # Выполним установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present
      allow_unauthenticated: yes
      update_cache: yes

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
